### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by CauaSCP**

### CODE REVIEW

**Comment by Repulser** [comment]
:eyes: youre definitely doing it wrong

**Comment by Plutoberth** [comment]
Not sure how to respond to this

**Comment by Repulser** [comment]
Just clap

**Comment by GigaFyde** [comment]
_insert slow clap_

**Comment by napstr** [comment]
Shouldn't this have been covered by https://blog.github.com/2018-04-18-new-tools-for-open-source-maintainers/#accidental-and-drive-through-pull-request-prevention :thinking:

**Comment by YaBoyWonder** [comment]
👏

**Pull request closed without merging**
